blank_issues_enabled: false
contact_links:
  - name: You have a question?
    url: https://github.com/alexandra-c/leaflet-tracking-marker/discussions/new
    about: Not sure about something and you need help from us or from the community? Please ask and answer questions here.
